### PR TITLE
Convert website to Hugo

### PR DESCRIPTION
**Pull request by mullikine**
This converts the website to Hugo and adds a nice theme.

It has been tested using an Apache2 VirtualHost.

preview

### CODE REVIEW

**Comment by veb** [comment]
hey @mullikine sorry I didn't see this (I didn't realise I hadn't been logged into my own github account for a while).

I just want to know why Hugo? I assume it'll still work with github pages?

I doubt anybody would have a problem with me merging I assume!

**Comment by mullikine** [comment]
Hey Mike,

Yes in theory it should just work. I tested on an apache virtual host with
the same domain name.

I switched to hugo because I use it in my other websites
http://mullikine.github.io/
https://semiosis.github.io/
https://infogetics.github.io/

It was an easy conversion, they have a million themes, etc.
They have the most themes, so switching theme is very easy.

I wanted to pick something that wouldn't take any time to update because
I've automated the process.

**Comment by veb** [comment]
I've never used Hugo before. If I accept this PR will everything magically happen?

**Comment by mullikine** [comment]
In theory, yes. I did my best to make sure of that. Otherwise, I can submit
another pull request.

**Pull request closed without merging**
